[AC-5050] - Add prerequisites and installation instructions for the new deployment and build system
masschallenge/impact-api pull request #136
Opened 2018-04-22 11:58 UTC by yotammanor

2018-04-25 17:47 UTC, pbx requested changes
Good stuff, thanks again. My notes are mostly copy edits.

2018-04-25 17:47 UTC, pbx commented on README.md
> +To stop to server, run `make stop-server` as well.
"To stop the server"

2018-04-25 17:47 UTC, pbx commented on README.md
> +`make run-serer debug=0`
s/serer/server/

2018-04-25 17:47 UTC, pbx commented on README.md
> +Impact-api is configured such that every successful travis build
Cap "Travis"

2018-04-26 11:39 UTC, yotammanor commented on README.md
> +This should be done whenever the requirements change.
added a more elaborate example.

2018-04-26 11:40 UTC, yotammanor commented on README.md
> +* Note that these commands will delete the DB, so any
done

2018-04-26 11:42 UTC, yotammanor commented on README.md
> +`make run-server-1`
They're all equivalent. Added that statement explicitly.

2018-04-26 11:44 UTC, yotammanor commented
@pbx addressed your comments.

2018-04-26 16:36 UTC, pbx requested changes
Great changes, I just have one remaining point of confusion.

2018-04-26 16:36 UTC, pbx commented on README.md
> +`make run-server-1`
If they're equivalent, why do we introduce the alternative form here? Is there a downside to simply using `make run-server` as the prescribed command here?

2018-04-27 09:26 UTC, yotammanor commented
@pbx re your last question - I was seeing it as an opportunity to introduce the available synonyms. They are all referring to the same implementation.

2018-04-27 13:43 UTC, pbx commented
@yotammanor - another way to put my question is, what benefit does the developer reading this documentation gain from learning that `make run-server-1` is effectively an alias for `make run-server`? It feels like we are surfacing a Makefile implementation detail. This is not a big point by any means, I'm just focusing on making the experience of learning our tooling as smooth as possible for engineers new to it. 

If you feel like showing both names for this command is really the right thing to do, I don't need to die on this hill. I could live with it being merged as-is.

2018-04-29 07:15 UTC, yotammanor commented
@pbx clarified that the other commands are aliases.

2018-04-30 13:48 UTC, pbx approved these changes

2018-04-30 13:48 UTC, merged