[AC-5622] Add API calls for Criterion and CriterionOptionSpec
masschallenge/impact-api pull request #166
Opened 2018-06-21 04:55 UTC by jonkiparsky

* API calls exist for list and detail, including patch and post
* calls work as expected 
* decided to use mixins to reduce code duplication and avoid tangled inheritance messes. we may need to develop standards around sane usage of mixin classes to avoid future design issues. (either as part of this ticket, or on a new ticket)

2018-06-22 20:34 UTC, mc-nathan commented
Functional issue:
It seems wrong to me that according to the OPTIONS the POST for Criterion does not expect a judging round id:

2018-06-22 20:35 UTC, mc-nathan commented
`judging_round_id` is also missing from the OPTIONS for the PATCH on a specific Criterion.

2018-06-22 20:39 UTC, mc-nathan commented
Functional issue: The `id` should never get patched, but it's in the OPTIONS for the PATCH.

2018-06-22 20:47 UTC, mc-nathan commented
Looks like this is strictly an issue with the OPTIONS since the actual PATCH call does take `judging_round_id` and rejects calls that specify `id`.

2018-06-22 20:49 UTC, mc-nathan commented
Functional issue: `count`, `weight` and `criterion_id` are missing from the OPTIONs for the CriterionOptionSpec POST.
```
        "POST": {
            "type": "object",
            "properties": {
                "option": {
                    "type": "string",
                    "required": true
                }
            }
        }
```

2018-06-22 20:50 UTC, mc-nathan commented
Similarly for PATCH, the `count`, `weight` and `criterion_id` are missing and `id` is listed.

2018-06-22 21:08 UTC, mc-nathan requested changes
Some minor code-ish stuff, but some important functional issues.

2018-06-26 18:41 UTC, jonkiparsky commented on web/impact/impact/v1/helpers/user_helper.py
> +    def valid_keys(cls, user_type, post=False):
okay

2018-06-27 19:48 UTC, mc-nathan approved these changes

2018-06-27 20:08 UTC, merged