[AC-4708] - Impact coverage report is not diff-aware
masschallenge/impact-api pull request #17
Opened 2017-08-09 14:02 UTC by yotammanor

**Changes Introduced in [AC-4708](https://masschallenge.atlassian.net/browse/AC-4708):**

- rewrite coverage targets to print a diff-aware report.
- rewrite coverage targets to be more similar to the equivalent accelerate aliases.
- add target coverage-html-open as a separate command from coverage-html.

**To test:**
- on development, change a .py file, run `make coverage`. You'll see the entire file tree printed.
- on branch, `make coverage` (change included :) ). You'll see just that file being printed. Also, html won't open automatically.
- change a file in tests/django_migrations/non-.py file, and it won't be printed.

2017-08-09 16:11 UTC, mc-nathan requested changes
Remove change to user_role.py or make it clear why it's being made here and not in accelerate.

2017-08-09 16:11 UTC, mc-nathan commented on web/impact/impact/models/user_role.py
> +    OFFICE_HOUR_ROLES = {AIR,
This change is not in Accelerate and seems irrelevant to this PR.

2017-08-10 06:32 UTC, yotammanor commented
@mc-nathan reverted the utility commit, and updated testing instructions above.

2017-08-10 12:15 UTC, mc-nathan approved these changes

2017-08-11 14:35 UTC, knittingarch requested changes
Functional Issues
On the branch, the changed file doesn't show up after running `make coverage`.

Code: Looks good.
Code Quality: Clean.
Tests: Pass
Coverage: N/A

2017-08-11 14:36 UTC, knittingarch commented
<img width="768" alt="screen shot 2017-08-11 at 10 33 13 am" src="https://user-images.githubusercontent.com/7423975/29217836-deca2cba-7e80-11e7-8e63-fa6dfa4688f7.png">

2017-08-11 19:44 UTC, mc-nathan commented
I was only able to reproduce the behavior reported by @knittingarch by making a change to a file that already had full coverage in a way that it still has full coverage (e.g., add a blank line).  This seems reasonable to me.  I learned that the change that @knittingarch made was to change a True to a False in permission.py  which probably didn't change the coverage.  She's going to test a bit further.

2017-08-11 19:45 UTC, knittingarch approved these changes

2017-08-11 19:45 UTC, merged