[AC-5666] - Person profile page 0.1 - End of Sprint Stretch
masschallenge/impact-api pull request #175
Opened 2018-07-03 17:09 UTC by yotammanor

**Changes Introduced in [AC-5666](https://masschallenge.atlassian.net/browse/AC-5666):**
- Add graphql fields to support the functionality added in https://github.com/masschallenge/directory/pull/80
- Allow the expert profile to be served from impact api

**Test:**
- See test instructions on other PR.
- Re accessing the expert profile:
  -  try to go to accelerate.masschallenge.org/directory/expert/1000/ - this won't work
  - try to go to test4.masschallenge.org/directory/expert/1000/ - assuming AC-5666 is deployed, it will work (and serve an older copy of the directory, so don't rely on the result for functional review of the directory PR)

2018-07-09 15:10 UTC, shanbady requested changes

2018-07-09 15:10 UTC, shanbady commented on web/impact/impact/graphql/types/expert_profile_type.py
> +def get_user_programs(user):
mark this as a private method _get_user_programs

2018-07-13 10:01 UTC, yotammanor commented
@shanbady ready for re-review.

2018-07-13 15:03 UTC, shanbady approved these changes

2018-07-13 15:03 UTC, merged