[AC-5836] Add API call for cloning criteria
masschallenge/impact-api pull request #183
Opened 2018-07-24 21:02 UTC by jonkiparsky

To test: Create a new judging round and get its id, call this TARGET. Find a judging round for which criteria exist and get its id, call this SOURCE. 
hit http://localhost:8000/api/v1/clone_criteria/SOURCE/TARGET to clone criteria

http://localhost:8000/api/v1/criterion/?judging_round=SOURCE
should return the original criteria
http://localhost:8000/api/v1/criterion/?judging_round=TARGET
should return the new criteria

2018-08-06 19:53 UTC, shanbady requested changes

2018-08-06 19:53 UTC, shanbady commented on web/impact/impact/v1/views/clone_criteria_view.py
> +    def get(self, request, source_pk, target_pk):
since we are creating a new resource this should be a 'post' method rather than a GET since get requests should not alter state.

2018-08-06 19:53 UTC, shanbady commented on web/impact/impact/v1/views/clone_criteria_view.py
> +        self._validate_judging_round_exists(target_pk)
not sure if the permission checking is handled upstream somewhere but does this protect against non-staff users making calls?

2018-08-07 17:39 UTC, shanbady commented
@jonkiparsky looks like there is aconflict to resolve. otherwise looks good.

2018-08-08 17:48 UTC, jonkiparsky commented
@shanbady conflict resolved, added a test, back to you

2018-08-09 16:04 UTC, shanbady approved these changes

2018-08-09 16:05 UTC, merged