AC-5775: add office hours availability to bnew profile page
masschallenge/impact-api pull request #186
Opened 2018-07-31 17:13 UTC by shanbady

This PR adds an "officehoursUrl" attribute to the graphql response as part of https://github.com/masschallenge/directory/pull/84

2018-08-02 14:16 UTC, yotammanor requested changes
a few small requests, mostly good.

2018-08-02 14:16 UTC, yotammanor commented on web/impact/impact/graphql/types/expert_profile_type.py
> +        now = timezone.now()
something I just noticed - a user who sees their own profile page should also see available mentor office hours (currently it isn't the case). and also superusers, probably.

2018-08-02 21:00 UTC, shanbady commented on web/impact/impact/graphql/types/expert_profile_type.py
> +            ).latest('created_at')
i previously had it this way but it threw a 'program role grant does not exist' exception

2018-08-02 21:00 UTC, shanbady commented on web/impact/impact/graphql/types/expert_profile_type.py
> +                date__gt=now)).exists()
done

2018-08-02 21:00 UTC, shanbady commented on web/impact/impact/__init__.py
> +__version__ = '1.0.1'
reverted

2018-08-03 15:53 UTC, pbx commented on web/impact/impact/graphql/types/expert_profile_type.py
> +            ).latest('created_at')
seems like there's a middle ground there though. 
```
mentor_grant_qs = self.user.programrolegrant_set.filter(
                program_role__user_role__name=UserRole.MENTOR
            )
if mentor_grant.qs.exists():
    latest_grant = mentor_grant_qs.latest()
    # do stuff
```

2018-08-03 16:10 UTC, pbx commented on web/impact/impact/graphql/types/expert_profile_type.py
> +            ).latest('created_at')
Seems like there's a middle ground: 
```python
mentor_grants = self.user.programrolegrant_set.filter(
                program_role__user_role__name=UserRole.MENTOR
            )
if mentor_grants.exists():
    latest_grant = mentor_grants.latest('created_at')
    # do stuff
```

2018-08-05 07:52 UTC, yotammanor approved these changes
Thanks for picking up the changes!

2018-08-06 08:34 UTC, merged