[AC-4677-api] Change field definitions to mirror mc models
masschallenge/impact-api pull request #20
Opened 2017-08-14 14:53 UTC by jonkiparsky

ProgramRole.name, NamedGroup.name, UserLabel.label, and StartupLabel.label should all have same length

To review: check model changes, verify that migrations (both here and accelerate side) are correct

Note that as of Aug 14 none of the affected fields has a length > 50.

2017-08-15 18:12 UTC, shanbady requested changes

2017-08-15 18:12 UTC, shanbady commented on web/impact/impact/models/program_role.py
> +    name = models.CharField(max_length=255, unique=True, db_index=True)
shouldnt we be using the constant defined in utils?

2017-08-15 18:21 UTC, jonkiparsky commented on web/impact/impact/models/program_role.py
> +    name = models.CharField(max_length=255, unique=True, db_index=True)
Good call, fixed

2017-08-15 19:06 UTC, mc-nathan approved these changes

2017-08-15 19:06 UTC, mc-nathan commented
@shanbady MAW

2017-08-18 14:11 UTC, shanbady approved these changes

2017-08-18 14:11 UTC, merged