[AC-5919] Add Clearance-based permission checks for allocator API calls
masschallenge/impact-api pull request #202
Opened 2018-08-24 18:43 UTC by jonkiparsky

* added mechanism for Clearance-based permission checks on impact-api
** note that this mechanism duplicates some code from accelerate, and uses a slightly different approach. I did try to hoist up the ClearanceManager and some code from permission_checks to django-accelerator, so it could be shared between accelerate and impact, but this failed due to cross-repo model sharing issues. 
* added Global Operations Manager permission checks on analyze_judging_round and clone_criteria API calls
* altered test settings to squelch logging output (otherwise, it echoed with test output)
* If this work is acceptable, will update AC-5924 with the details of these changes to preserve memory

To test: 
* verify that the added tests are reasonable
* replicate the added tests by hitting these endpoints with users holding just v1 permissions, and with users holding global ops manager clearance. Should fail and succeed, respectively.

2018-09-05 18:44 UTC, pbx commented
I have a review in progress but am pausing it while i work on urgent https://masschallenge.atlassian.net/browse/AC-5970

2018-09-06 14:49 UTC, pbx requested changes
(Removed a note I had written about this not working -- user error! I had failed to add my user to `v1_clients` so I was getting only 403s)

2018-09-06 14:56 UTC, pbx approved these changes

2018-09-06 14:59 UTC, pbx requested changes
I resolved my previous "request changes" review when I fixed my functional problem, then remembered a couple minor things I noted in it that still could use attention. So, back in "request changes" for the moment.

2018-09-07 20:50 UTC, jonkiparsky commented on web/impact/impact/permissions.py
> +# TO DO: resolve this duplication
Won't fix. Any useful hint would require tracing back through a bunch of things I tried two weeks ago, which are no longer in my head. I'll assume that the comment is enough indication that some attempt has been made and has failed. Hopefully that will warn off the optimists.

2018-09-07 20:56 UTC, jonkiparsky commented on web/impact/impact/tests/test_analyze_judging_round_view.py
> +    def test_global_operations_permission_required(self):
renamed this test.

2018-09-07 20:56 UTC, jonkiparsky commented on web/impact/impact/permissions.py
> +from accelerator_abstract.models.base_clearance import (
done

2018-09-10 15:32 UTC, pbx approved these changes

2018-09-10 15:32 UTC, merged