Ac 5928: Create functional accelerate Dockerfile
masschallenge/impact-api pull request #212
Opened 2018-09-20 15:15 UTC by VincentHokie

**Changes introduced in [AC-5928](https://masschallenge.atlassian.net/browse/AC-5887)**:
- add mysql setting to allow accelerate work off it

**How to setup**:
- create a connection file in the `./mysql` directory in impact
- run the following commands in sequence
- `make shutdown-vms`
- `docker ps -a`
- pick out the mysql container and `docker rm <container id>`
- run `make run-server`

2018-09-21 19:18 UTC, shanbady requested changes

2018-09-21 19:54 UTC, VincentHokie commented on .gitignore
> +mysql/connection/
Yeah, I can make this happen.

2018-09-21 19:57 UTC, VincentHokie commented on .gitignore
> +mysql/connection/
Done.

2018-09-24 13:51 UTC, shanbady approved these changes

2018-09-24 13:51 UTC, merged