AC-6023: Mentor Directory - Should only show confirmed Alumni Mentors to Alumni Entrepreneurs
masschallenge/impact-api pull request #217
Opened 2018-10-01 12:13 UTC by VincentHokie

**Changes introduced in AC-6023**:
- ensure algolia filters respect alumni status

**How to Test**:
- visit [test 4](https://test4.masschallenge.org) and masquerade as `001@livemile.com`  who has been given ProgramRoleGrants to the Alum Program, if you visit the directory you will notice that `001@livemile.com` only sees `Ted William Regan` who is the only confirmed mentor in the `Global Almuni Program`. 

Feel free to poke around the directory in different use-cases
- as staff
- as an Enterpreneur who is not a finalist and is not an alumni either
- as an Enterpreneur who is both a finalist an alumni

- **Currently**, Enterpreneurs of an ended program still see the mentors of those programs on the directory

2018-10-01 15:10 UTC, jonkiparsky requested changes
Some changes I'd like to see here. The basic logic looks fine.

2018-10-01 16:39 UTC, VincentHokie commented on web/impact/impact/views/algolia_api_key_view.py
> +    participant_roles = _enterpreneur_specific_alumni_filter(
Fixed.

2018-10-01 16:39 UTC, VincentHokie commented on web/impact/impact/views/algolia_api_key_view.py
> +def _enterpreneur_specific_alumni_filter(roles, request):
Fixed. Arigato.

2018-10-01 16:39 UTC, VincentHokie commented on web/impact/impact/views/algolia_api_key_view.py
> +    current_finalist_roles = ProgramRoleGrant.objects.filter(
Yes, you are being picky :)

2018-10-01 16:40 UTC, VincentHokie commented on web/impact/impact/views/algolia_api_key_view.py
> +            request.user.baseprofile.user_type == ENTREPRENEUR_USER_TYPE:
Thanks!

2018-10-01 16:40 UTC, VincentHokie commented on web/impact/impact/tests/test_algolia_api_key_view.py
> +        for _ in range(5):
Done.

2018-10-01 16:48 UTC, VincentHokie commented on web/impact/impact/tests/test_algolia_api_key_view.py
> +    def _create_user_with_base_profile(self, user_type=ENTREPRENEUR_USER_TYPE):
I'll address the related concerns here. I totally understand what you mean, my qn is this. The [base_user_role.py](https://github.com/masschallenge/django-accelerator/blob/development/accelerator_abstract/models/base_user_role.py) defines `FINALIST_USER_ROLES` as
```
FINALIST_USER_ROLES = [FINALIST, AIR, STAFF]
```
One approach would be to only add this `FINALIST_USER_ROLES` when we wan't like you suggest. Correct me if I'm wrong, but wouldn't this block both `STAFF ` and `AIR` users? which I believe we don't want.

2018-10-01 16:49 UTC, VincentHokie commented on web/impact/impact/views/algolia_api_key_view.py
> +    participant_roles = UserRole.FINALIST_USER_ROLES + [
I'll address the related concerns here. I totally understand what you mean, my qn is this. The [base_user_role.py](https://github.com/masschallenge/django-accelerator/blob/development/accelerator_abstract/models/base_user_role.py) defines `FINALIST_USER_ROLES` as
```
FINALIST_USER_ROLES = [FINALIST, AIR, STAFF]
```
One approach would be to only add this `FINALIST_USER_ROLES` when we wan't like you suggest. Correct me if I'm wrong, but wouldn't this block both `STAFF ` and `AIR` users? which I believe we don't want.

2018-10-01 16:50 UTC, VincentHokie commented on web/impact/impact/tests/test_algolia_api_key_view.py
> +    def _create_user_with_base_profile(self, user_type=ENTREPRENEUR_USER_TYPE):
I remember touching this, don't quite remember why I let it go. Let me look into it again.

2018-10-01 17:28 UTC, VincentHokie commented on web/impact/impact/tests/test_algolia_api_key_view.py
> +    def _create_user_with_base_profile(self, user_type=ENTREPRENEUR_USER_TYPE):
Used the `EntrepreneurFactory` as suggested, had to do some (tinkering)[https://github.com/masschallenge/impact-api/pull/217/files#diff-0d59e84ae0ac9f57ab89230e71dee0cfR182] to ensure the existing login functionality works as expected.

2018-10-10 09:53 UTC, VincentHokie commented on web/impact/impact/views/algolia_api_key_view.py
> +    participant_roles = UserRole.FINALIST_USER_ROLES + [
I've implemented your concerns best I could, let me know if this is what you had in mind.

2018-10-10 12:10 UTC, jonkiparsky approved these changes
Looks fine - if we had time, I'd ask you to address the duplication, but I suppose someone will factor that out further on down the road.

2018-10-10 12:10 UTC, merged