AC-6533: Add 'keepdb' option to Makefile test targets
masschallenge/impact-api pull request #292
Opened 2019-05-15 10:52 UTC by VincentHokie

#### Changes introduced in [AC-6533](https://masschallenge.atlassian.net/browse/AC-6533)
- add keepdb option to 'make test' to allow a user opt out of keeping the db while running tests

#### How to test
- checkout this branch
- run `time make test tests=mcproject.mc_apply.tests.test_applicant_view:TestApplicantView.test_preceding_and_trailing_spaces_in_names_are_removed` twice, and notice the second time, the test db is not recreated (the first time, the db is actually created)
- now run `time make test tests=mcproject.mc_apply.tests.test_applicant_view:TestApplicantView.test_preceding_and_trailing_spaces_in_names_are_removed keepdb=no` and notice a prompt appears asking you to destroy the existing db.

2019-05-15 19:08 UTC, pbx requested changes
This needs an update to `target_help` explaining the `keepdb` option.

2019-05-16 15:11 UTC, VincentHokie commented
thanks, added

2019-05-16 17:46 UTC, pbx approved these changes

2019-05-17 12:15 UTC, kitaka commented
@VincentHokie @pbx 
Given that people have been accustomed to running tests with keepdb off, why don't we maintain that as the default and making keepdb on as the option?

2019-05-17 13:34 UTC, kitaka commented
Also, running `make test` the first time - passes but on the second run given the reused DB - it fails. That's not good behaviour to have in a default state.

2019-05-17 15:35 UTC, pbx commented
@kitaka - the default is a matter of taste, and I'm fine with what the team prefers, but personally I prefer having `--keepdb` _on_ by default. It's what I am going to want 9 out of 10 times (if not more) when I am running tests locally. 

Re the errors on subsequent runs, I've seen that but don't have a good recipe for recreating _or_ fixing. Can you share repro steps?

2019-05-17 15:38 UTC, jonkiparsky commented
Drive-by comment: Errors on subsequent runs indicate that a test is not sufficiently isolated. This is useful information and we should use it to fix any tests that fail in this manner.

2019-05-17 16:25 UTC, kitaka commented
> Drive-by comment: Errors on subsequent runs indicate that a test is not sufficiently isolated. This is useful information and we should use it to fix any tests that fail in this manner.

You raise a good point. If the cost is acceptable, then I have no reservations.

2019-05-20 13:48 UTC, VincentHokie commented
haven't been able to reproduce that failing test, how do I repro?

I tied running `make test` twice.

2019-05-21 16:04 UTC, merged