[AC-6779] People Directory - Inactive users should not appear for community members (especially inactive staff)
masschallenge/impact-api pull request #299
Opened 2019-06-14 08:56 UTC by mkiterian

### Changes introduced in [AC-6779](https://masschallenge.atlassian.net/browse/AC-6779):
- add the is_active field to the people index

### Dependency
This has a sibling PR here https://github.com/masschallenge/accelerate/pull/2209 that should merge first. The people indices for staging and prod should be reindexed once these have merged

### How to test
- Logged in as a staff member e.g [staff](https://test4.masschallenge.org/admin/simpleuser/user/43639/masquerade/) go to the [people index on test4](https://test4.masschallenge.org/people). Search for an inactive account e.g John Harthorne's. You should be able to see the result.
- Repeat the above process with a non staff user e.g [user](https://test4.masschallenge.org/admin/simpleuser/user/26766/masquerade/). John Harthorne's profile should not appear in the results
- Other QA stuff

2019-06-14 16:06 UTC, kitaka requested changes

2019-06-14 16:06 UTC, kitaka commented on web/impact/impact/views/algolia_api_key_view.py
> +def _build_filter(*args):
@mkiterian did you consider something like;
```python
return " AND ".join(args)
```

2019-06-14 16:06 UTC, kitaka commented on web/impact/impact/tests/test_algolia_api_key_view.py
> +                self.assertTrue(IS_ACTIVE_FILTER in response_data["filters"])
@mkiterian for Python3's case we might want to use `self.assertIn` or `self.assertNotIn`

2019-06-14 16:07 UTC, kitaka requested changes

2019-06-14 16:07 UTC, kitaka commented on web/impact/impact/tests/test_algolia_api_key_view.py
> +    def test_staff_user_does_not_have_is_active_filter(self):
@mkiterian there seems to be some duplication in the tests, refactor the common pieces into a different function/method.

2019-06-15 13:39 UTC, VincentHokie approved these changes
✅

2019-06-17 12:00 UTC, kitaka approved these changes

2019-06-17 12:01 UTC, merged