[AC-6851] People Directory - Use people profile IDs not Team member IDs
masschallenge/impact-api pull request #314
Opened 2019-07-09 16:59 UTC by kitaka

**Changes Introduced in [AC-6851](https://masschallenge.atlassian.net/browse/AC-6851):**
-

**Test:**

_On development_
-

_checkout this branch_
-

2019-07-11 16:11 UTC, mkiterian commented
Taking code

2019-07-11 19:27 UTC, kaymation approved these changes
Tried to break the directory using the search bar but i couldnt! approved

2019-07-12 13:55 UTC, mkiterian commented
@kitaka what's special about `des pieri`?

2019-07-12 14:51 UTC, mkiterian requested changes
Code changes look good. Minor cleanup requested

2019-07-12 14:51 UTC, mkiterian commented on web/impact/impact/tests/test_graphql.py
> +            self.assertIn(ENTREPRENEUR_NOT_FOUND_MESSAGE, error_messages)
the name of this test should also be updated

2019-07-12 16:25 UTC, kitaka commented
> @kitaka what's special about `des pieri`?

Des Pieri is an expert; and since the original implementation only linked to profiles of startup team members, he's profile wasn't available. For that reason, he provided a good test case.

2019-07-16 08:22 UTC, mkiterian approved these changes
Looks good

2019-07-16 08:22 UTC, merged