AC 7765
masschallenge/impact-api pull request #419
Opened 2020-05-21 17:37 UTC by PrinceDavis

## [AC-7766](https://masschallenge.atlassian.net/browse/AC-7765)

**Changes introduced:**
- Make GraphQL return locations of program families a user is attached to

**Testing**
- Login as a staff or user with staff clearance or a finalist in an active program
- [launch the graphql endpoint](http://localhost/graphql/)
Confirm that:
- queries for `officeHourLocations` returns requested fields

**Sibling PRs**
coming soon

2020-05-27 12:11 UTC, geofrocker commented
Resolve merge conflicts

2020-05-28 10:09 UTC, iankigen commented
Doing QA

2020-05-28 10:38 UTC, geofrocker approved these changes
Code looks good

2020-05-28 14:23 UTC, iankigen requested changes
you have some lint issues. I'm not sure why it is not failing the CI:
```
web/impact/impact/graphql/types/base_user_profile_type.py:6:1: F401 'accelerator.models.ProgramRole' imported but unused
web/impact/impact/graphql/types/base_user_profile_type.py:21:1: E302 expected 2 blank lines, found 1
web/impact/impact/graphql/types/base_user_profile_type.py:43:5: E303 too many blank lines (2)
web/impact/impact/graphql/types/base_user_profile_type.py:50:80: E501 line too long (112 > 79 characters)
web/impact/impact/graphql/types/entrepreneur_profile_type.py:14:1: E302 expected 2 blank lines, found 1
web/impact/impact/graphql/types/location_type.py:2:1: F401 'graphene' imported but unused
web/impact/impact/graphql/types/location_type.py:18:1: W391 blank line at end of file
web/impact/impact/tests/test_graphql.py:6:1: F401 'accelerator.models.Location' imported but unused
web/impact/impact/tests/test_graphql.py:153:9: F841 local variable 'judge_role_grant' is assigned to but never used
web/impact/impact/tests/test_graphql.py:766:80: E501 line too long (112 > 79 characters)
web/impact/impact/tests/test_graphql.py:802:5: E303 too many blank lines (3)
```

2020-05-28 15:43 UTC, iankigen requested changes
From QA:
- An `officehour_location` field is added to BaseUserProfileType class ✅ 
- A resolver function is created to resolve queries for the new field ✅ 
- The new function returns a  list of distinct location objects for the logged in users or the provided user ✅ 
    - The list displays duplicate location objects.
- This list should contain all of the Locations associated with Program Families for which the user either holds Staff clearance or has an office-hour related User Role [Mentor, AIR, Finalist] in an active program ✅ 
- Remote location is added to the end of location objects ✅ 
    - Remote location is not added to the end of location objects

2020-05-28 18:54 UTC, iankigen commented
include tests for:
- Remote location is added to the end of location objects 
- The new function returns a list of distinct location objects for the logged in users or the provided user

2020-06-03 12:39 UTC, iankigen commented on web/impact/impact/graphql/types/base_user_profile_type.py
> +        remote = Location.objects.filter(name__icontains='remote').first()
This implementation is prone to errors. Other locations ie `<Location Jerusalem | Israel Remote>` have remote in their name.

2020-06-03 12:40 UTC, iankigen commented on web/impact/impact/graphql/types/base_user_profile_type.py
> +            programfamilylocation__program_family_id__in=ids).distinct()
`remote` should be excluded in this query to avoid duplicate results

2020-06-03 12:45 UTC, iankigen requested changes

2020-06-03 12:45 UTC, iankigen commented on web/impact/impact/graphql/types/base_user_profile_type.py
> +        locations = [x for x in result]
this can be accomplished better by:
```
locations_list = list(result)
locations_list.append(remote)
```

2020-06-04 12:03 UTC, iankigen approved these changes

2020-06-04 12:04 UTC, merged