[AC-7811] P1 Fix Internal server error when canceling a non existing office hour reservation as finalist
masschallenge/impact-api pull request #429
Opened 2020-06-04 15:47 UTC by geofrocker

### Changes introduced in: [AC-7811](https://masschallenge.atlassian.net/browse/AC-7811) :
- Fix potential check_object_permissions failure with office-hour set to None
### How to test on test2
- masquerade as any finalist
- Make a post request on the CancelOfficeHourReservationView review with a non existing officehour id.
- Get the message `The specified office hour was not found.`

2020-06-05 18:14 UTC, iankigen commented
@geofrocker we have a failing test

2020-06-08 13:21 UTC, iankigen commented on web/impact/impact/tests/test_cancel_office_hour_reservation.py
> +        self.assertEqual(response.data, notification)
can we use the existing `self.assert_ui_notification(response, expected_success, expected detail)` format?

2020-06-08 17:15 UTC, iankigen approved these changes
Get the message `The specified office hour was not found` when trying to cancel a non-existing office hour as a finalist. ✅

2020-06-08 19:33 UTC, pbx requested changes
To save us merge conflicts when both this and AC-7469 (the New Monolith long-running branch) are merged, please update the imports in `test_cancel_office_hour_reservation.py` to match the relative form used there:
* https://github.com/masschallenge/impact-api/blob/AC-7469/web/impact/impact/tests/test_cancel_office_hour_reservation.py

2020-06-10 12:45 UTC, pbx approved these changes

2020-06-10 15:02 UTC, jonkiparsky approved these changes

2020-06-10 15:02 UTC, merged