[AC-7729] API endpoint to reserve office hours
masschallenge/impact-api pull request #436
Opened 2020-06-09 19:01 UTC by jonkiparsky

https://masschallenge.atlassian.net/browse/AC-7729

2020-06-10 13:23 UTC, iankigen requested changes

2020-06-11 10:18 UTC, geofrocker requested changes
### A few issues for clean up
While on clean db, I did the following:
- I schedule office hours on behalf of this [mentor](http://localhost:8181/admin/simpleuser/user/1032/masquerade/)
- I masqueraded as this [finalist](http://localhost:8181/admin/simpleuser/user/13884/masquerade/) and successfully reserved an open office hour ✅
- I got the expected response but the startup field was empty yet the user has an associated startup ❌ ie
 ```javascript
"timecard_info": {
        "finalist_first_name": "User-First-13884",
        "finalist_last_name": "User-Last-13884",
        "topics": "",
        "startup": ""
    }
```
- I got an expected error message when I tried to reserve a non-existent office hour ie `No such office hour exists.` ✅
- I got an expected error message when I tried to reserve an already office hour ie `That session has already been reserved` ✅
- I got an expected error message when I tried to use a non-existent user ie `No such user exists` ✅
- I got an expected error message when I tried to use a non-existent startup ie `No such startup exists` ✅
- Startup id is required by the endpoint but not used for anything apart from checking that the startup exists ❌
- A user can pass any startup id that exists in the database and make a successful API call ❌

2020-06-11 15:57 UTC, jonkiparsky commented
@geofrocker The "startup" field gets the startup that the user has selected for this office hour. It does not attempt to find a startup for the user. This is intentional, since the code will not have the information needed to make a sensible decision in this case.

2020-06-11 16:43 UTC, jonkiparsky commented
@iankigen can you give more specific details on what you'd like the success header and detail to be?

2020-06-11 16:44 UTC, jonkiparsky commented on web/impact/templates/emails/reserve_office_hour_email_to_mentor.html
> +{{ office_hour_date_time | date }} (office_hour_date_time : date:"%Z" }}
Please be more specific

2020-06-11 16:55 UTC, iankigen commented
```
{
header: Office Hours session reserved on {data} (in  "day, date month, year" format if possible)
detail: with {mentor}, {mentor title} at {mentor company}
}
```
@jonkiparsky I think this format conforms to the mockup details.

2020-06-11 17:34 UTC, iankigen commented on web/impact/templates/emails/reserve_office_hour_email_to_mentor.html
> +{{ office_hour_date_time | date }} (office_hour_date_time : date:"%Z" }}
we have a syntax error ln@4 `(office_hour_date_time : date:"%Z" }}
`

2020-06-11 18:12 UTC, jonkiparsky commented on web/impact/impact/v1/views/reserve_office_hour_view.py
> +        self.office_hour.finalist = self.target_user
👍

2020-06-11 18:12 UTC, jonkiparsky commented on web/impact/impact/v1/views/reserve_office_hour_view.py
> +        self.office_hour.save()
👍

2020-06-11 18:12 UTC, jonkiparsky commented on web/impact/impact/v1/views/reserve_office_hour_view.py
> +def _variable_name(field_name):
👍

2020-06-11 19:26 UTC, iankigen approved these changes

2020-06-11 19:40 UTC, iankigen requested changes

2020-06-11 19:40 UTC, iankigen commented on web/impact/impact/permissions/v1_api_permissions.py
>          return (super().has_permission(request, view) or
can we check for is_employee user status?

2020-06-12 12:55 UTC, iankigen approved these changes
Code looks good

2020-06-12 15:38 UTC, geofrocker commented
Looks good ✅

2020-06-12 15:39 UTC, geofrocker approved these changes

2020-06-12 15:39 UTC, merged