[AC-4642b] - Add Overview Start and End Times to the Program model
masschallenge/impact-api pull request #44
Opened 2017-09-28 10:42 UTC by yotammanor

**Changes Introduced [AC-4642b](https://masschallenge.atlassian.net/browse/AC-4642):**

- add new fields to Program.
- remove deprecated field from Program.

**Test:**
- in impact-api, `make dev`
- in accelerate, checkout AC-4642a.
- run `resetdb`
- then dump the db: `mysqldump -u root -proot mc_dev | gzip > /vagrant/db_cache/initial_schema_AC_4642a.sql.gz`
- in impact-api, in a new terminal, run `make load-db GZ_FILE=../accelerate/db_cache/initial_schema_AC_4642a.sql.gz`
- login to browsable API as demoadmin, go to http://localhost:8000/api/impact/Program/
- see that the new fields are added, and that the old field is removed.

**Note:**
- AC-4642b should be deployed in impact-api only after AC-4642a is deployed in accelerate.
- AC-4642c in accelerate should be deployed only after AC-4642b.

2017-09-29 18:02 UTC, jonkiparsky requested changes
This change does not agree with the change on the AC-4642a PR. (accepting_company_overviews field is not deleted there)

2017-09-29 19:27 UTC, yotammanor commented
This is on purpose. Impact api needs to change first, before the migration
is applied (which is done in AC-4642c)

On Sep 29, 2017 9:02 PM, "Jon Kiparsky" <notifications@github.com> wrote:

> *@jonkiparsky* requested changes on this pull request.
>
> This change does not agree with the change on the AC-4642a PR.
> (accepting_company_overviews field is not deleted there)
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/masschallenge/impact-api/pull/44#pullrequestreview-66227086>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AE6LQXTs8S0qsZ5WY4-Mqs3stOjpUgLAks5snTDFgaJpZM4PnER4>
> .
>

2017-09-29 20:35 UTC, pbx approved these changes
Works for me. I do think we need a more explicit deployment outline to follow when we're reviewing multi-branch, multi-repo stories like this.

2017-10-04 13:28 UTC, jonkiparsky approved these changes

2017-10-04 13:28 UTC, merged