[AC-7891] - P0: [New office hours] Staff unable to create and view office hours
masschallenge/impact-api pull request #447
Opened 2020-06-25 19:33 UTC by iankigen

## [AC-7891](https://masschallenge.atlassian.net/browse/AC-7891)

**Changes introduced**
- allow staff users with clearance to view location choices, program families and be able to hold office hour sessions

**Testing**
- As a staff user with staff clearance in an active program
- go to http://localhost:8000/api/v1/office_hours_calendar/, confirm that the response data has the correct user `location_choices` and `mentor_program_families`
- go to http://localhost:8000/api/v1/office_hour/, confirm that the staff user is able to create an office hour session

2020-06-29 13:36 UTC, geofrocker commented
I realized an inconsistency in staff office hour creation. There was a case where office hours created by staff were not seen by a mentor. this could be data issue though.will approve once I resolve this

2020-06-29 16:03 UTC, shakirandagire requested changes

2020-06-29 16:03 UTC, shakirandagire commented on web/impact/impact/v1/serializers/office_hours_serializer.py
> +        if staff_user == mentor:
This if statement is a bit confusing since it is checking if a staff_user is a mentor.
Could you rename it better

2020-06-29 16:42 UTC, shakirandagire reviewed
Code changes look good to me.  Will approve and waiting on the QA request by @geofrocker

2020-06-29 17:44 UTC, geofrocker approved these changes
looks good ✅
- As a staff user with staff clearance in an active program, I was able to create an office hour ✅

2020-06-30 12:20 UTC, shakirandagire approved these changes

2020-06-30 12:21 UTC, merged