[AC-7908] P0: [New office hours] /office_hours_calendar/ endpoint includes null values in timezones list
masschallenge/impact-api pull request #448
Opened 2020-06-26 13:17 UTC by iankigen

## [AC-7908](https://masschallenge.atlassian.net/browse/AC-7908)

**Changes introduced**
- Exclude null values in timezone list

**Testing**
- As a user with office hours, go to http://localhost:8000/api/v1/office_hours_calendar/
- choose one office hour session id in the `calendar_data` and set its location to None (shell/admin console)
- On development:
  - Confirm that `null` is included in the timezone list
- On this branch
  - Confirm that `null` is excluded in the timezone list

2020-06-26 15:36 UTC, PrinceDavis approved these changes

2020-06-29 16:32 UTC, jonkiparsky requested changes
Test needs to be improved, otherwise looks fine.

2020-06-29 17:50 UTC, iankigen commented
@jonkiparsky I have implemented the requested changes

2020-06-29 17:57 UTC, jonkiparsky approved these changes

2020-06-30 11:02 UTC, merged