[AC-7923] P0: [New office hours] Some staff unable to create and view office hours
masschallenge/impact-api pull request #457
Opened 2020-07-06 18:59 UTC by iankigen

## [AC-7923](https://masschallenge.atlassian.net/browse/AC-7923)

**Changes introduced**
- Allow all users with clearances in an active program to create and view office hours

**Testing**
- As a user with any staff clearance in an active program
- go to http://localhost:8000/api/v1/office_hours_calendar/, confirm that the response data has the correct user `location_choices` and `mentor_program_families`
- go to http://localhost:8000/api/v1/office_hour/, confirm that the staff user is able to create an office hour session

2020-07-06 19:12 UTC, jonkiparsky requested changes
Looks good, a little de-duplication of the tests would be nice

2020-07-06 19:12 UTC, jonkiparsky commented on web/impact/impact/tests/test_create_edit_office_hours_view.py
> +    def test_user_with_pom_clearance_can_create_office_hours(self):
```
    def assert_user_with_clearance_can_create_office_hours(self, clearance_level):
        program_family = ProgramFactory().program_family
        staff_user = self.staff_user(program_family=program_family,
                                     level=clearance_level)
        data = self._get_post_request_data(staff_user)
        with self._assert_office_hour_created():
            self._create_office_hour_session(staff_user, data)

    def test_user_with_staff_clearance_can_create_office_hours(self):
       self.assert_user_with_clearance_can_create_office_hours(CLEARANCE_LEVEL_STAFF)

# etc for each clearance level
```

2020-07-06 19:12 UTC, jonkiparsky commented on web/impact/impact/tests/test_office_hours_calendar_view.py
> +    def test_user_with_pom_clearance_sees_own_office_hour(self):
```
    def assert_user_with_clearance_sees_own_office_hour(self, clearance_level):
        program = ProgramFactory()
        staff_user = self.staff_user(program_family=program.program_family,
                                     level=clearance_level)
        office_hour = self.create_office_hour(mentor=staff_user)
        response = self.get_response(user=staff_user)
        self.assert_hour_in_response(response, office_hour)


    def test_user_with_pom_clearance_sees_own_office_hour(self):
        self.assert_user_with_clearance_sees_own_office_hour(CLEARANCE_LEVEL_POMl):
       
    # etc for other clearance levels

2020-07-07 14:22 UTC, jonkiparsky approved these changes

2020-07-07 14:22 UTC, jonkiparsky approved these changes
Code looks great.

2020-07-08 18:12 UTC, PrinceDavis approved these changes

2020-07-08 18:12 UTC, merged