re-ordering url includes
masschallenge/impact-api pull request #509
Opened 2020-10-05 19:53 UTC by shanbady

This PR fixes a url resolution error in the monolith api.

To test:

1- visit the endpoint on a current release (https://accelerate.masschallenge.org/api/oauth/token/) - note that it fails with a 503
2 - I have this deployed to test3 currently. visit the test3 version (https://test3.masschallenge.org/api/oauth/token/) and note that it responds with a 402 (expected response for that route) which indicates the url is resolving properly. 
3 - similarly the graphql endpoint gives a 404 on production (https://accelerate.masschallenge.org/api/graphql/) but will give an appropriate response on test3 (https://test3.masschallenge.org/api/graphql/)

2020-10-05 20:31 UTC, pbx commented
@shanbady I'm thinking about how to get this deployed. Seems to me we'll also need an accelerate PR that updates the submodule to commit `4ceb9ba5f`, and we'll need to roll a new release. 

If you have ideas for a faster path to production (that don't leave us in a messy state) I'm interested.

2020-10-05 20:41 UTC, pbx requested changes
@shanbady this looks good, but I want to double check before  merge because I'm not seeing the response codes you named in steps 1 and 2. 

#1 `accelerate.masschallenge.org/api/oauth/token/` gives me a 404 rather than a 503.
#2 `test3.masschallenge.org/api/oauth/token/` gives me a (Cloudflare) 405 rather than a 402
#3 (These URLS do respond as you describe)

2020-10-05 20:46 UTC, pbx commented
(In the interest of getting this merged -- since @philophilo and @PrinceDavis will both be in before me tomorrow, either one of them can approve if they see fit, and I'll dismiss my review)

2020-10-06 11:33 UTC, PrinceDavis requested changes
The outcome of my review is same result as @pbx 

#1 `accelerate.masschallenge.org/api/oauth/token/` returns 404 rather than a 503.
#2 `test3.masschallenge.org/api/oauth/token/`returns 405 rather than a 402
#3  graphQL endpoint works as expected

2020-10-06 13:22 UTC, shanbady commented
@pbx @philophilo 

- I had a mistake in the test instructions - 405 is the expected response for /api/oauth/token  (it requires a post for it to be valid)
- The actual errors (the 500) actually come from staging not production (which presumably doesn't have the merged api code). I've updated the test instructions with the corrections.

2020-10-06 14:22 UTC, pbx approved these changes
The code change looks good to me and I'm satisfied to merge this.

2020-10-06 14:32 UTC, PrinceDavis approved these changes

2020-10-06 14:48 UTC, merged