AC-5067: Fix 500 for GET of /v1/user/35908 (or any user without a profile)
masschallenge/impact-api pull request #67
Opened 2017-11-14 02:55 UTC by mc-nathan

Work done:
- Code was fixed to work with users that have no profile objects.

To test:
- `make reset-remote-db`
- Grant the appropriate permissions to a super user account.  E.g., `make grant-permissions PERMISSION_USER=13514-user@example.com PERMISSION_CLASSES=v1_clients`
- Login as that user.  E.g., 13514-user@example.com
- Visit http://localhost:3000/v1/user/35908
- On development it should generate a 500 and on the branch it should be fine.
- Try other calls with this user or with any of the other "broken" users (39658, 38978, 41341, and 44399)

2017-11-14 16:53 UTC, yotammanor requested changes
one bad name test, otherwise all is good and as advertised.

2017-11-14 16:53 UTC, yotammanor commented on web/impact/impact/tests/test_user_detail_view.py
> +    def test_patch_profile_file_with_no_profile(self):
name seems to be erroneous. `profile_file` bit.

2017-11-14 16:56 UTC, pbx approved these changes
Confirmed error on development and absence thereof on the branch.

2017-11-15 17:30 UTC, yotammanor approved these changes

2017-11-15 17:30 UTC, merged