[AC-5038-impact] JUST FOR YOTAM Configure impact-api to manage models, add initial migration
masschallenge/impact-api pull request #91
Opened 2018-01-11 17:55 UTC by jonkiparsky

See AC-5038-mcproject for review information

2018-01-21 08:05 UTC, yotammanor reviewed
Blocking comment here, some more below

2018-01-21 08:17 UTC, yotammanor commented on web/impact/requirements/base.txt
> +git+https://github.com/masschallenge/django-accelerator.git@AC-5038-njw#egg=django-accelerator
Note that this is different from the version in AC-5038-mcproject (plus it is not a release)

2018-01-21 14:08 UTC, yotammanor requested changes
Functional review is in the mcproject branch.

Some comments:
- We should probably set codeclimate to ignore migrations somehow. I'm ok with ignoring it manually for the moment.
- We should rename `0002_auto...` to a more meaningful name.

2018-01-21 14:08 UTC, yotammanor commented on web/impact/impact/models/utils.py
> +    return True
I don't like the fact that the boolean flag is configured in settings.py in one project and is set literally in the other.

2018-01-22 01:36 UTC, jonkiparsky commented
re: migration names, clearly we're going to have to improve `make migrations` to take the option set that `./manage.py makemigrations` allows

2018-01-22 07:26 UTC, yotammanor commented
@jonkiparsky my suggestion is that we should just have a `make manage` that allows for an arbitrary manage.py command, with its args and kwargs as needed. Here: https://masschallenge.atlassian.net/browse/AC-4598?focusedCommentId=37873&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-37873

2018-01-23 11:46 UTC, yotammanor commented
@jonkiparsky @mc-nathan closing this PR, and renaming AC-5038-impact to `modular-models-epic`

2018-01-23 11:46 UTC, closed without merging